apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
  labels:
    app.kubernetes.io/part-of: ai-native-paas-runtime
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
